#!/usr/bin/env bash
# build and install clas12root
# - additional arguments will be passed to `cmake`, such as build options
set -euo pipefail
cmake -B build -S . "$@"
cmake --build build
cmake --install build
